DROP TABLE IF EXISTS GF_User;
DROP TABLE IF EXISTS GF_Group;
DROP TABLE IF EXISTS GF_Invitation;

CREATE TABLE GF_Group(
	idGroup				BIGINT			NOT NULL	PRIMARY KEY		AUTO_INCREMENT,
	groupName			VARCHAR(45)		NOT NULL	DEFAULT ''		UNIQUE,
	groupDescription	TEXT			NOT NULL,
	version				BIGINT				NOT NULL	DEFAULT 1
);

CREATE TABLE GF_User(
	idUser				BIGINT			NOT NULL	PRIMARY KEY		AUTO_INCREMENT,
	userName			VARCHAR(45)		NOT NULL	UNIQUE,
	password			VARCHAR(45)		NOT NULL,
	firstName			VARCHAR(45)		NOT NULL	DEFAULT '',
	lastName			VARCHAR(45)		NOT NULL	DEFAULT '',
	isAdmin				BOOLEAN			NOT NULL	DEFAULT FALSE,
	version				BIGINT				NOT NULL	DEFAULT 1,
	GroupID				BIGINT,
	FOREIGN KEY (GroupID) 	REFERENCES GF_Group(idGroup) 	ON DELETE SET NULL
);

CREATE TABLE GF_Invitation(
	inviterID			BIGINT			NOT NULL,
	inviteeID			BIGINT			NOT NULL,
	groupID				BIGINT			NOT NULL,
	PRIMARY KEY(inviterID, inviteeID),
	FOREIGN KEY(inviterID) 	REFERENCES GF_User(idUser) 		ON DELETE CASCADE,
	FOREIGN KEY(inviteeID) 	REFERENCES GF_User(idUser) 		ON DELETE CASCADE,
	FOREIGN KEY(groupID) 	REFERENCES GF_Group(idGroup) 	ON DELETE CASCADE
);
